spring.datasource.url=jdbc:postgresql://localhost:5432/springrestapi
spring.datasource.username=postgres
spring.datasource.password=local1234
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect